# Task 1: Pi with output-sized script Write a script to output the same number of PI digits as the size of your script. Say, if your script size is 10, it should print 3.141592653.


# Task 2: You are given a file containing a list of words (case insensitive 1 word per line) and a list of letters. Print each word from the file that can be made using only letters from the list. You can use each letter only once (though there can be duplicates and you can use each of them once), you don’t have to use all the letters.